set(CTEST_PROJECT_NAME "vv_itk4")
set(CTEST_NIGHTLY_START_TIME "1:00:00 UTC")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "my.cdash.org")
set(CTEST_DROP_LOCATION "/submit.php?project=VV")
set(CTEST_DROP_SITE_CDASH TRUE)
